services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - healthchain_data:/usr/src/app/data
    restart: unless-stopped

volumes:
  healthchain_data:
    driver: local 